import type { Metadata } from "next";
import {
    Great_Vibes,
    Noto_Serif_TC,
    Bangers,
    Goblin_One,
    Open_Sans,
} from "next/font/google";
import "./globals.css";

const greatVibes = Great_Vibes({
    weight: "400",
    variable: "--font-great-vibes-nf",
    subsets: ["latin"],
});

const notoSerifTC = Noto_Serif_TC({
    weight: "400",
    variable: "--font-noto-serif-tc-nf",
    subsets: ["latin"],
});

const bangers = Bangers({
    weight: "400",
    variable: "--font-bangers-nf",
    subsets: ["latin"],
});

const goblinOne = Goblin_One({
    weight: "400",
    variable: "--font-goblin-one-nf",
    subsets: ["latin"],
});

const openSans = Open_Sans({
    variable: "--font-open-sans-nf",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="it"
            className={`${greatVibes.variable} ${notoSerifTC.variable} ${bangers.variable} ${goblinOne.variable} ${openSans.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">{children}</body>
        </html>
    );
}
